name: laboratoareIA
channels:
  - defaults
dependencies:
  - asttokens=3.0.0=py310haa95532_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.1=py310haa95532_0
  - debugpy=1.8.16=py310h885b0b7_1
  - decorator=5.2.1=py310haa95532_0
  - exceptiongroup=1.3.0=py310haa95532_0
  - executing=2.2.1=py310haa95532_0
  - expat=2.7.3=h9214b88_0
  - ipykernel=6.30.1=py310haa95532_0
  - ipython=8.30.0=py310haa95532_0
  - jedi=0.19.2=py310haa95532_0
  - jupyter_client=8.6.3=py310haa95532_0
  - jupyter_core=5.8.1=py310haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.1.7=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py310haa95532_1
  - parso=0.8.4=py310haa95532_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=py310haa95532_0
  - prompt-toolkit=3.0.52=py310haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310h02ab6af_1
  - pure_eval=0.2.3=py310haa95532_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - pywin32=311=py310h885b0b7_0
  - pyzmq=27.1.0=py310h7149c55_1
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py310haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py310h827c3e9_0
  - traitlets=5.14.3=py310haa95532_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - defusedxml==0.7.1
      - fastjsonschema==2.21.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fqdn==1.5.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - isoduration==20.11.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - keras==3.12.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - namex==0.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.17.0
      - overrides==7.7.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - protobuf==6.33.0
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - wrapt==2.0.0
prefix: C:\Users\ANDREI\anaconda3\envs\laboratoareIA
